BV: handle failures in proxy and monitoring stages
SUSE/susemanager-ci pull request #1110
Opened 2024-02-06 14:49 UTC by NamelessOne91

Closes https://github.com/SUSE/susemanager-ci/issues/1108

Docs for the sh global function state this about using returnStatus

>  Normally, a script which exits with a nonzero status code will cause the step to fail with an exception. If this option is checked, the return value of the step will instead be the status code. You may then compare it to zero, for example

Currently most of the steps for the proxy save the returnStatus to a variable but don't use it to determine whether a failure occurred or not. The same holds true for the monitoring server.
Only the MUs stages will properly fail if a script execution does not return with 0.

2024-02-07 09:44 UTC, Bischoff approved these changes
please don't merge until Maxime had a look

2024-02-20 12:59 UTC, ktsamis approved these changes
I remember fixing something similar in normal BV only but that's a good idea to do everywhere. The exit code is anyway taken into account in jenkins as a failed step and it fails the stage but why not be explicit everywhere? This makes sense to me

2024-02-20 14:30 UTC, srbarrios commented
To run as much as we can of our Build Validation, we intentionally decided to don't stop the pipeline in some stages. As an example, if monitoring stage fails, that's not a reason to stop run the boostrap of all our minions. In theory, we have stored the result and we expose it at the end of the pipeline.
But I would agree to fail the whole pipeline if all the team agree on that way of proceeding.

In any case, if we decide to fail in one of those stages changed in this PR, then we better also refactor some code like:

https://github.com/SUSE/susemanager-ci/blob/master/jenkins_pipelines/environments/common/pipeline-build-validation.groovy#L17-L20
https://github.com/SUSE/susemanager-ci/blob/master/jenkins_pipelines/environments/common/pipeline-build-validation.groovy#L187-L190
https://github.com/SUSE/susemanager-ci/blob/master/jenkins_pipelines/environments/common/pipeline-build-validation.groovy#L292-L303

2024-02-21 18:01 UTC, NamelessOne91 commented
Refactored & Rebased

The "standard" BV pipeline should now fail whenever a stage fails.
The only exception is when a failure occurs in a stage that is being run in parallel ( as of now: clients testing):  the interested parallel "branch" should be marked as failing and terminate but the pipeline should continue running the other branches and the following stages.

I also did a minor refactor around the checks on pipeline params like  `must_create_X` and `enable_X' in order to not display at all stages which are  not running any test.

I'll push my local changes to the AWS BV pipeline once we agree on these ones and we decide to have the same (or another) behavior there.

2024-02-22 11:16 UTC, ktsamis approved these changes

2024-03-05 02:29 UTC, maximenoel8 commented
|| I also did a minor refactor around the checks on pipeline params like must_create_X and enable_X in order to not create and display at all stages which are not running any test.

We are keeping all the stages even if they are skip for a better vision in the main jenkins view ( when you open the build ).
If the number of stages change, it will wipe the other stages from the view.

It was an explicit demands from @Bischoff

2024-03-05 02:31 UTC, maximenoel8 commented
I'm against reverting the stages change. We had a long discussion about it and we decided to keep the skip stages visible.

2024-03-05 02:37 UTC, maximenoel8 commented
I'm also against removing the try / catch mechanism. This will stop the pipeline when we don't want. Having a failing stage is putting the stage in red and at the end if any stages failed the pipeline is red.

Let's organize a meeting to understand the need of this full refactor.

We reach this point by iteration and those changes are removing lot of features that were added later after long discussion with the team.

2024-03-05 02:38 UTC, maximenoel8 requested changes
I don't really understand the need of those changes and it reverts the improvements added during the use of the BV pipeline by the team.

2024-03-05 02:42 UTC, maximenoel8 commented on jenkins_pipelines/environments/common/pipeline-build-validation.groovy
>                      res_products = sh(script: "./terracumber-cli ${common_params} --logfile ${resultdirbuild}/testsuite.log --runstep cucumber --cucumber-cmd 'unset ${nodesHandler.envVariableListToDi
If the issue is related to reposync failing, we probably only need to change this for : 
sh "./terracumber-cli ${common_params} --logfile ${resultdirbuild}/testsuite.log --runstep cucumber --cucumber-cmd 'unset ${nodesHandler.envVariableListToDisable.join(' ')}; ${env.exports} cd /root/spacewalk/testsuite; rake cucumber:build_validation_reposync'"

2024-03-05 02:46 UTC, maximenoel8 commented
Did you test your changes ? Tried the different scenarios ?

2024-03-05 07:58 UTC, srbarrios commented
I agree with @maximenoel8 points of view.

2024-03-05 09:32 UTC, NamelessOne91 commented
> I don't really understand the need of those changes and it reverts the improvements added during the use of the BV pipeline by the team.

To give some context, the actual issues we had are the ones mentioned in the first comment: some proxy (and monitoring) stages where still marked as green even when failing. 
That's due to us not checking the status code returned by sh commands in those stages, I don't know whether that's intentional or just something that slipped through in the past.
Anyway, the PR was limited to that scope initially.

After discussing it, there has been a request to see if could make the pipeline fail-fast as that would have been closer to the workflow some of us adopt anyway.

> I'm against reverting the stages change. We had long discussions about it and we decided to keep the skip stages visible.

That's actually something I did on my initiative, so I'm totally fine reverting my changes and keep stages that are skipped still visible. I can see the point in doing so.

All that said, it'll be perfectly fine for me to freeze the refactor and/or discard it entirely.
I think the only issue that actually might have to be addressed is the one mentioned in the 1st comment .

2024-03-05 12:44 UTC, srbarrios commented
FMPOV, the only remarkable improvement is to fail the full pipeline if the proxy fails, as it's a strong dependency for all the onboarding of clients. But I don't know if we missed this behavior in our refactor or it was made in purpose.

Let's have a quick discussion tomorrow after the planning meeting?

2024-03-06 02:49 UTC, maximenoel8 commented
I was playing around today with the pipeline, I think we are missing an error for those stages : 
 - Add Activation Keys Proxy
 - Create bootstrap repository Proxy
 - Bootstrap Proxy
 - Add Activation Keys Monitoring
 - Create bootstrap repository Monitoring
 - Bootstrap Monitoring Server
Adding a step for those stages either using : 
```
                    if (res_XXXX != 0) {
                        error("Stage fails ${res_XXXX}")
                    }
```

or 

```
                    sh "exit ${res_XXX}"
```

should do the trick.

2024-03-06 09:32 UTC, NamelessOne91 commented
Closing as we agreed to only add the proxy stages failures and make the pipeline fail if they fail.

2024-03-06 09:32 UTC, closed without merging