Add support for 5.0 in json script
SUSE/susemanager-ci pull request #1117
Opened 2024-02-13 11:57 UTC by ktsamis

Added Alma 8 client tools.

Added 5.0 version in command line. For now 4.3 is still default.

Added 5.0 beta client tools. They will be separate from 4.3. They won't become common at any point even after GA. Until the betas are done we need 5.0 beta and non-beta client tools in the minions, they will get non-beta from the testsuite anyway but wanted to add the possibility of a parallel MI that has beta and non-beta, especially during 4.3 MU while a beta is running.

Added hardcoded 5.0 server and proxy repo. Unfortunately for this we won't be getting MIs but only directly updating this url with the latest. 

Added possibility for mi_ids to be separated by spaces as well as comma. 

I know it's a bit hacky and long now but a refactor has to wait a bit until the necessary functions work and I have time

2024-02-20 16:33 UTC, deneb-alpha requested changes
First round of review from my side.  

Until we split the client tools between 4.3 and 5.0 I  think the script should be ok.  
in any case, I left a few suggestions

2024-02-20 16:33 UTC, deneb-alpha commented on jenkins_pipelines/scripts/maintenance_json_generator.py
>      "debian10_minion": "/SUSE_Updates_Debian_10-CLIENT-TOOLS_x86_64/",
Debain10 is gone 
```suggestion
```

2024-02-20 16:33 UTC, deneb-alpha commented on jenkins_pipelines/scripts/maintenance_json_generator.py
> +    "debian10_minion": "/SUSE_Updates_Debian_10-CLIENT-TOOLS-BETA_x86_64/",
Debian 10 is EOL
```suggestion
```

2024-02-22 12:16 UTC, ktsamis commented on jenkins_pipelines/scripts/maintenance_json_generator.py
>      "debian10_minion": "/SUSE_Updates_Debian_10-CLIENT-TOOLS_x86_64/",
Removed, thanks Marina

2024-02-22 12:16 UTC, ktsamis commented on jenkins_pipelines/scripts/maintenance_json_generator.py
> +    "debian10_minion": "/SUSE_Updates_Debian_10-CLIENT-TOOLS-BETA_x86_64/",
Removed, thanks :)

2024-02-22 12:30 UTC, Bischoff approved these changes
approving but i'm unable to really judge the details

2024-02-22 12:59 UTC, deneb-alpha approved these changes

2024-02-22 13:22 UTC, merged