QE: Add openSUSE 15.6 support
SUSE/susemanager-ci pull request #1182
Opened 2024-04-05 09:16 UTC by vandabarata

Related to https://github.com/SUSE/spacewalk/issues/23848

2024-04-05 09:20 UTC, vandabarata commented
The failed checks aren't related to my changes so that probably isn't anything to worry about

2024-04-05 10:31 UTC, srbarrios commented on terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env5.tf
> +  images = ["rocky9o", "opensuse155o", "opensuse156o", "sles15sp4o", "ubuntu2204o"]
We need to change all the changes matching `opensuse156o` by `opensuse156armo`

2024-04-05 10:36 UTC, Bischoff requested changes
see remarks

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/SUSEManager-4.3-PRV.tf
> +  images = ["centos7o", "opensuse155o", "opensuse156o", "sles15sp4o", "ubuntu2204o"]
not for CI (yet)

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env5.tf
> +  images = ["rocky9o", "opensuse155o", "opensuse156o", "sles15sp4o", "ubuntu2204o"]
I don't know about tests on PRs. Ask Jordi.

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/SUSEManager-4.3-NUE.tf
> +  images = ["centos7o", "opensuse155o", "opensuse156o", "sles15sp4o", "ubuntu2204o"]
not for CI (yet)

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/SUSEManager-4.3-SLE-update.tf
> +  images      = [ "sles15sp4o", "opensuse155o", "opensuse156o" ]
I don't think so

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/SUSEManager-4.3-refenv-NUE.tf
> +  images = ["centos7o", "opensuse155o", "opensuse156o", "sles15sp4o", "ubuntu2204o"]
probably not

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/SUSEManager-Head-NUE.tf
> +  images = ["rocky8o", "opensuse155o", "opensuse156o", "ubuntu2204o", "sles15sp4o", "slemicro55o"]
not for CI

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/Uyuni-Master-K3S.tf
> +  images = ["rocky8o", "opensuse155o", "opensuse156o", "leapmicro55o", "ubuntu2204o", "sles15sp4o"]
not for CI

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/Uyuni-Master-PRV.tf
> +  images = ["rocky8o", "opensuse155o", "opensuse156o", "ubuntu2204o", "sles15sp4o"]
not for CI

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/Uyuni-Master-podman.tf
> +  images = ["rocky8o", "opensuse155o", "opensuse156o", "leapmicro55o", "ubuntu2204o", "sles15sp4o"]
not for CI (yet)

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf
> +  images = ["rocky8o", "opensuse155o", "opensuse156o", "ubuntu2204o", "sles15sp4o"]
I don't think so

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/Uyuni-Master-tests-code-coverage.tf
> +  images = ["rocky8o", "opensuse155o", "opensuse156o", "ubuntu2204o", "sles15sp4o"]
Probably not

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/tfvars/PR-testing-manager43.tfvars
> +IMAGES                 = ["rocky9o", "opensuse155o", "opensuse156o", "sles15sp4o", "ubuntu2204o"]
ask Jordi, but probably not

2024-04-05 10:36 UTC, Bischoff commented on terracumber_config/tf_files/SUSE-Manager-4.3-PR-tests-env6.tf
> +  images = ["rocky9o", "opensuse155o", "opensuse156o", "sles15sp4o", "ubuntu2204o"]
same

2024-04-16 09:02 UTC, nodeg commented on terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf
> +  install_salt_bundle = true
It is fine to leave it in. We take care of the issues with a Salt cleanup in the test suite.

2024-04-25 14:31 UTC, nodeg requested changes
See remarks. Furthermore, adjustment in the `main.tf` file for the Uyuni BV in NUE are missing :wink:

2024-04-25 14:31 UTC, nodeg commented on terracumber_config/tf_files/SUSEManager-4.3-SLE-update.tf
> +  images      = [ "sles15sp4o", "opensuse155o"]
I think this is a mistake and the whitespace at the end should be there. It is intentional, like after the beginning bracket.

2024-04-25 14:31 UTC, nodeg commented on terracumber_config/tf_files/SUSEManager-4.3-build-validation-NUE.tf
> +  images      = [ "sles12sp5o", "sles15sp1o", "sles15sp2o", "sles15sp3o", "sles15sp4o", "sles15sp5o", "slemicro51-ign", "slemicro52-ign", "slemicro53-ign", "slemicro54-ign", "slemicro55o", "almalinux
I think this is a mistake and the whitespace at the end should be there. It is intentional, like after the beginning bracket.

2024-05-02 15:59 UTC, Bischoff approved these changes
I did not check the MACs. The rest looks good to me.

2024-05-03 09:01 UTC, nodeg approved these changes
LGTM overall. Thank you, Vanda!

2024-05-03 09:04 UTC, merged