WIP: add custom header when deploying
SUSE/susemanager-ci pull request #419
Opened 2021-12-02 16:08 UTC by jordimassaguerpla

2021-12-10 16:47 UTC, jordimassaguerpla commented
we see now this

![image](https://user-images.githubusercontent.com/1148215/145610331-5ba46491-26d1-4e5a-997b-0de4c9087bf2.png)

If we run "spacewalk-service restart" after the "deploy" phase. I run the command manually via ssh.

We could add that at the "remote-exec".

2021-12-20 17:15 UTC, jordimassaguerpla commented
This is how it looks 

![image](https://user-images.githubusercontent.com/1148215/146806134-b28fe058-4c1f-4789-80d2-ea260377dc4a.png)


![image](https://user-images.githubusercontent.com/1148215/146806195-cdf57cdb-9147-4781-aef4-561cfab8e8ad.png)

2021-12-20 17:16 UTC, jordimassaguerpla commented
@srbarrios Can you review this one?

2021-12-21 10:25 UTC, jordimassaguerpla commented
See the text states

"In case of FAILURE you can access the environment until XXXXX"

I am using terraform to change the "custom header" to include this information. This is happening on deploy time, so I can't know if tests have failed at this point, this is why I added the text "In case of FAILURE".

I tried injecting javascript code to have a count down, but it did not worked for the login page.

2021-12-21 10:33 UTC, jordimassaguerpla commented
@srbarrios I could try instead running a command at the end of the pipeline using for example paramiko https://www.paramiko.org/

2021-12-22 11:09 UTC, srbarrios requested changes
Better merge https://github.com/SUSE/susemanager-ci/pull/431

2021-12-23 17:06 UTC, merged